### ISSUE TITLE
Learning Rate Schedules

### ISSUE THREAD

**Issue by bnels** [DeepLearnPhysics/lartpc_mlreco3d#15]
It will likely be useful to have a way to schedule learning rates
e.g. in `*.cfg`
```yaml
training:
   learning_rate: [0.01, 0.001, 0.0001]
   iterations: [1000, 1000, 1000]
```
would do 1k iterations with learning rate at 0.01, then 1k iterations at learning rate 0.001, and so on
