### ISSUE TITLE
Log epoch calculation appears to be wrong

### ISSUE THREAD

**Issue by bnels** [DeepLearnPhysics/lartpc_mlreco3d#26]
Relevant part of config file:
```yaml
  dataset:
    name: LArCVDataset
    data_dirs:
      - /gpfs/slac/staas/fs1/g/neutrino/kterao/data/dlprod_ppn_v10/combined
    data_key: train_512px
    limit_num_files: 10
```
If I run for 1000 iterations with batch size 8, epoch is logged as 0.8.  However, I have only seen 8000 events out of about 80k, so epoch should be 0.1.
